name: Build

on:
  push:
    branches:
      - main

jobs:

  checkout:
    name: Get sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: sources
          path: ./

  build:
    name: Create build
    needs: checkout
    runs-on: ubuntu-latest
    steps: 

      - uses: actions/download-artifact@v2
        with:
          name: sources
          path: ./

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install
      - run: npm test