name: Deploy on serveur

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      server_name:
        required: true
        type: string

    secrets:
      dockerhub_token:
        required: true
      dockerhub_username:
        required: true
      server:
        required: true
      serveur_user:
        required: true
      serveur_pwd:
        required: true
      serveur_port:
        required: true

jobs:
  prod:
    name: ${{ inputs.server_name }}
    runs-on: ubuntu-latest
    steps:

      - name: SSH on ${{ inputs.server_name }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.server }}
          username: ${{ secrets.serveur_user }}
          password: ${{ secrets.serveur_pwd }}
          port: ${{ secrets.serveur_port }}
          script: |
            echo Login
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            echo Delete image
            docker rm -f $(docker ps -a | grep ${{ inputs.server_name }} | awk '{print $1}')

            echo Pull image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.server_name }}:${{ inputs.image_tag }}

            echo Run new one
            docker run -d -p 3000:80 --name squaddev ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.server_name }}:${{ inputs.image_tag }}